# Generated by Django 4.2.9 on 2024-06-20 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_userwallet_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='userwallet',
            name='balance',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
