# Generated by Django 4.2.9 on 2024-06-21 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_payment_payment_date_payment_payment_period_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userwallet',
            old_name='created_at',
            new_name='date_created',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='payment_date',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='payment_period',
        ),
    ]
