# Generated by Django 4.2.9 on 2024-06-21 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0003_alter_plan_title'),
        ('payments', '0006_rename_created_at_userwallet_date_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='duration',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='payment',
            name='plan',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='plans.plan'),
            preserve_default=False,
        ),
    ]
