# Generated by Django 4.2.9 on 2024-06-21 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_payment_duration_payment_plan'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payments',
        ),
    ]
