# Generated by Django 4.2.9 on 2024-07-01 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0014_alter_payment_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='userwallet',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
