# Generated by Django 4.2.9 on 2024-11-29 13:09

import coupon.helpers
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AllowedUsersRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('all_users', models.BooleanField(default=False, verbose_name='All users?')),
                ('users', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='Users')),
            ],
            options={
                'verbose_name': 'Valid User',
                'verbose_name_plural': 'Valid Users',
            },
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=coupon.helpers.get_random_code, max_length=12, unique=True, verbose_name='Coupon Code')),
                ('times_used', models.IntegerField(default=0, editable=False, verbose_name='Usage Count')),
                ('created', models.DateTimeField(editable=False, verbose_name='Coupon Creation date')),
            ],
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(default=0, verbose_name='Value')),
                ('is_percentage', models.BooleanField(default=False, verbose_name='Is percentage?')),
            ],
            options={
                'verbose_name': 'Discount',
                'verbose_name_plural': 'Discounts',
            },
        ),
        migrations.CreateModel(
            name='MaxUsesRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_uses', models.BigIntegerField(default=0, verbose_name='Maximum Usage')),
                ('is_infinite', models.BooleanField(default=False, verbose_name='Infinite Usage?')),
                ('uses_per_user', models.IntegerField(default=1, verbose_name='Usage per user')),
            ],
            options={
                'verbose_name': 'Coupon Usage Condition',
                'verbose_name_plural': 'Coupon Usage Conditions',
            },
        ),
        migrations.CreateModel(
            name='ValidityRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expiration_date', models.DateTimeField(verbose_name='Expiration date')),
                ('is_active', models.BooleanField(default=False, verbose_name='Is active?')),
            ],
            options={
                'verbose_name': 'Coupon Exipiration',
                'verbose_name_plural': 'Coupon Exipirations',
            },
        ),
        migrations.CreateModel(
            name='Ruleset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allowed_users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coupon.allowedusersrule', verbose_name='Valid Users')),
                ('max_uses', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coupon.maxusesrule', verbose_name='Max Usage Count')),
                ('validity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coupon.validityrule', verbose_name='Coupon Expiration')),
            ],
            options={
                'verbose_name': 'Coupon Validation',
                'verbose_name_plural': 'Coupon Validation',
            },
        ),
        migrations.CreateModel(
            name='CouponUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('times_used', models.IntegerField(default=0, editable=False, verbose_name='Usage Count')),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coupon.coupon', verbose_name='Coupon')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Coupon User',
                'verbose_name_plural': 'Coupon Users',
            },
        ),
        migrations.AddField(
            model_name='coupon',
            name='discount',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coupon.discount'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='ruleset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coupon.ruleset', verbose_name='Coupon Validation'),
        ),
    ]
