# Generated by Django 4.2.9 on 2024-03-31 22:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('affiliates', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RefererSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('referer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referer_subscription', to='affiliates.referer')),
            ],
        ),
    ]
