# Generated by Django 4.2.9 on 2024-04-21 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('affiliates', '0003_affiliate_affiliatesubscription_useraffiliate_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='affiliatesubscription',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Affiliate Subscription', 'verbose_name_plural': 'Affiliate Subscriptions'},
        ),
        migrations.AlterModelOptions(
            name='referee',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Affiliate Referee', 'verbose_name_plural': 'Affiliate Referees'},
        ),
        migrations.AlterModelOptions(
            name='useraffiliate',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Affiliate User', 'verbose_name_plural': 'Affiliate Users'},
        ),
    ]
