# Generated by Django 4.2.9 on 2024-06-23 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('affiliates', '0008_alter_affiliatesubscription_subscription_period'),
    ]

    operations = [
        migrations.RenameField(
            model_name='affiliate',
            old_name='affiliate_type',
            new_name='title',
        ),
    ]
