# Generated by Django 4.2.9 on 2024-06-23 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiliates', '0009_rename_affiliate_type_affiliate_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affiliate',
            name='title',
            field=models.CharField(choices=[('free', 'Free'), ('gold', 'Gold')], default='free', max_length=30, unique=True),
        ),
    ]
