# Generated by Django 4.2.9 on 2024-06-23 22:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiliates', '0010_alter_affiliate_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='affiliatesubscription',
            options={'ordering': ['-created'], 'verbose_name': 'Affiliate Subscription', 'verbose_name_plural': 'Affiliate Subscriptions'},
        ),
        migrations.AlterModelOptions(
            name='referee',
            options={'ordering': ['-created'], 'verbose_name': 'Affiliate Referee', 'verbose_name_plural': 'Affiliate Referees'},
        ),
        migrations.AlterModelOptions(
            name='useraffiliate',
            options={'ordering': ['-created'], 'verbose_name': 'Affiliate User', 'verbose_name_plural': 'Affiliate Users'},
        ),
        migrations.RenameField(
            model_name='affiliatesubscription',
            old_name='timestamp',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='referee',
            old_name='timestamp',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='useraffiliate',
            old_name='timestamp',
            new_name='created',
        ),
        migrations.AddField(
            model_name='affiliate',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 6, 23, 22, 6, 25, 590653, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='affiliate',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='referee',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='useraffiliate',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='affiliatesubscription',
            name='subscription_period',
            field=models.CharField(choices=[('1', '1 Month'), ('2', '2 Months'), ('3', '3 Months'), ('4', '4 Months'), ('5', '5 Months'), ('6', '6 Months'), ('7', '7 Months'), ('8', '8 Months'), ('9', '9 Months'), ('10', '10 Months'), ('11', '11 Months'), ('12', '12 Months')], default='1', max_length=24, verbose_name='Subscription Period'),
        ),
    ]
