# Generated by Django 4.2.9 on 2024-07-25 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiliates', '0011_alter_affiliatesubscription_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraffiliate',
            name='referer_code',
            field=models.CharField(blank=True, editable=False, max_length=120, null=True),
        ),
    ]
