# Generated by Django 4.2.9 on 2024-07-25 17:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('affiliates', '0012_alter_useraffiliate_referer_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraffiliate',
            name='referer_code',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='useraffiliate',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_affiliate', to=settings.AUTH_USER_MODEL),
        ),
    ]
