# Generated by Django 4.2.9 on 2024-07-25 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiliates', '0013_alter_useraffiliate_referer_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraffiliate',
            name='referer_code',
            field=models.CharField(blank=True, editable=False, max_length=120, null=True),
        ),
    ]
