# Generated by Django 4.2.9 on 2024-04-21 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscription',
            options={'verbose_name': 'User Subscription', 'verbose_name_plural': 'User Subscriptions'},
        ),
        migrations.RenameField(
            model_name='plan',
            old_name='plan_type',
            new_name='title',
        ),
    ]
