# Generated by Django 4.2.9 on 2024-04-21 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0002_alter_subscription_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='title',
            field=models.CharField(choices=[('free', 'Free'), ('basic', 'Basic'), ('standard', 'Standard'), ('pro', 'Pro')], default='free', max_length=30, unique=True),
        ),
    ]
