# Generated by Django 4.2.9 on 2024-06-23 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0004_alter_subscription_subscription_period'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plan',
            old_name='title',
            new_name='plan_type',
        ),
    ]
