# Generated by Django 4.2.9 on 2024-06-23 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0005_rename_title_plan_plan_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='subscription_period',
            field=models.CharField(choices=[(1, '1 Month'), (2, '2 Months'), (3, '3 Months'), (4, '4 Months'), (5, '5 Months'), (6, '6 Months'), (7, '7 Months'), (8, '8 Months'), (9, '9 Months'), (10, '10 Months'), (11, '11 Months'), (12, '12 Months'), (13, '13 Months'), (14, '14 Months'), (15, '15 Months'), (16, '16 Months'), (17, '17 Months'), (18, '18 Months'), (19, '19 Months'), (20, '20 Months'), (21, '21 Month'), (22, '22 Months'), (23, '23 Months'), (24, '24 Months')], default=1, max_length=24, verbose_name='Subscription Period'),
        ),
    ]
