# Generated by Django 4.2.9 on 2024-06-23 13:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0006_alter_subscription_subscription_period'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='timestamp',
            new_name='created',
        ),
        migrations.AddField(
            model_name='userplan',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userplan',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='subscription_period',
            field=models.CharField(choices=[(1, '1 Month'), (2, '2 Months'), (3, '3 Months'), (4, '4 Months'), (5, '5 Months'), (6, '6 Months'), (7, '7 Months'), (8, '8 Months'), (9, '9 Months'), (10, '10 Months'), (11, '11 Months'), (12, '12 Months')], default=1, max_length=24, verbose_name='Subscription Period'),
        ),
    ]
