# Generated by Django 4.2.9 on 2024-06-23 14:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0007_rename_timestamp_subscription_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plan',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
