# Generated by Django 4.2.9 on 2024-06-23 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0008_plan_created_plan_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='subscription_period',
            field=models.CharField(choices=[('1', '1 Month'), ('2', '2 Months'), ('3', '3 Months'), ('4', '4 Months'), ('5', '5 Months'), ('6', '6 Months'), ('7', '7 Months'), ('8', '8 Months'), ('9', '9 Months'), ('10', '10 Months'), ('11', '11 Months')], default='1', max_length=24, verbose_name='Subscription Period'),
        ),
    ]
