# Generated by Django 4.2.9 on 2024-08-17 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0011_alter_subscription_subscription_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='title',
            field=models.CharField(choices=[('free', 'Free'), ('basic', 'Basic'), ('advance', 'Advance'), ('pro', 'Pro')], default='free', max_length=30, unique=True),
        ),
    ]
