# Generated by Django 4.2.9 on 2024-08-17 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0012_alter_plan_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plan',
            options={'ordering': ('price',)},
        ),
        migrations.AlterModelOptions(
            name='subscription',
            options={'ordering': ('created',), 'verbose_name': 'User Subscription', 'verbose_name_plural': 'User Subscriptions'},
        ),
        migrations.AlterModelOptions(
            name='userplan',
            options={'ordering': ('created',)},
        ),
    ]
