# Generated by Django 4.2.9 on 2024-04-07 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_course_level_thumbnail'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='thumbnail',
            options={'verbose_name': 'Upload Thumbnail', 'verbose_name_plural': 'Upload Thumbnails'},
        ),
        migrations.AlterModelOptions(
            name='upload',
            options={'verbose_name': 'Upload File', 'verbose_name_plural': 'Upload Files'},
        ),
        migrations.AlterModelOptions(
            name='uploadvideo',
            options={'verbose_name': 'Upload Video', 'verbose_name_plural': 'Upload Videos'},
        ),
    ]
