# Generated by Django 4.2.9 on 2024-06-30 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_course_created_course_image_course_updated'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activitylog',
            old_name='created_at',
            new_name='created',
        ),
        migrations.DeleteModel(
            name='Thumbnail',
        ),
    ]
