# Generated by Django 4.2.9 on 2024-07-08 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0011_alter_subscription_subscription_period'),
        ('courses', '0007_rename_created_at_activitylog_created_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='level',
        ),
        migrations.RemoveField(
            model_name='course',
            name='program',
        ),
        migrations.AddField(
            model_name='course',
            name='plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_plan', to='plans.plan'),
        ),
        migrations.DeleteModel(
            name='Program',
        ),
    ]
