# Generated by Django 4.2.9 on 2024-07-08 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_alter_course_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='grade',
            field=models.CharField(choices=[(0, 'Grade Zero'), (1, 'Grade One'), (2, 'Grade Two'), (3, 'Grade Three')], max_length=25, null=True),
        ),
    ]
