# Generated by Django 4.2.9 on 2024-07-09 17:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_alter_course_grade'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='image',
            new_name='cover_image',
        ),
        migrations.AddField(
            model_name='course',
            name='file',
            field=models.FileField(blank=True, help_text='Valid Files: pdf, docx, doc, xls, xlsx, ppt, pptx, zip, rar, 7zip', null=True, upload_to='course_files/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'docx', 'doc', 'xls', 'xlsx', 'ppt', 'pptx', 'zip', 'rar', '7zip'])]),
        ),
        migrations.AddField(
            model_name='course',
            name='video_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
