# Generated by Django 4.2.9 on 2024-07-09 18:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_rename_image_course_cover_image_course_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='video_link',
        ),
        migrations.AddField(
            model_name='course',
            name='video_id',
            field=models.CharField(help_text='Only input the video ID without the domain', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='file',
            field=models.FileField(blank=True, help_text='Valid Files: pdf, docx, doc, xls, xlsx, ppt, pptx,', null=True, upload_to='course_files/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'docx', 'doc', 'xls', 'xlsx', 'ppt', 'pptx'])]),
        ),
        migrations.AlterField(
            model_name='course',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=12),
        ),
    ]
