# Generated by Django 4.2.9 on 2024-07-14 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_remove_course_video_link_course_video_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='video_id',
            field=models.CharField(blank=True, help_text='Only input the video ID without the domain', max_length=200, null=True),
        ),
    ]
