# Generated by Django 4.2.9 on 2024-08-03 13:56

from django.db import migrations, models
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0017_alter_course_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='grade',
        ),
        migrations.AddField(
            model_name='course',
            name='video',
            field=embed_video.fields.EmbedVideoField(blank=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='slug',
            field=models.SlugField(blank=True, editable=False, unique=True),
        ),
    ]
