# Generated by Django 4.2.9 on 2024-08-03 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0019_course_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadvideo',
            name='course',
        ),
        migrations.DeleteModel(
            name='Upload',
        ),
        migrations.DeleteModel(
            name='UploadVideo',
        ),
    ]
