# Generated by Django 4.2.9 on 2024-08-03 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0020_remove_uploadvideo_course_delete_upload_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='video_id',
        ),
    ]
