# Generated by Django 4.2.9 on 2024-08-04 12:31

import courses.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0021_remove_course_video_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ('code', 'created')},
        ),
        migrations.RemoveField(
            model_name='course',
            name='file',
        ),
        migrations.AddField(
            model_name='course',
            name='upload_file',
            field=models.FileField(blank=True, help_text='Valid Files: Portable Documents File (PDF)', null=True, upload_to='course_files/', validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
        migrations.AlterField(
            model_name='course',
            name='cover_image',
            field=models.ImageField(blank=True, editable=False, null=True, upload_to='course_images/', validators=[courses.models.image_validator, django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg'])]),
        ),
    ]
