# Generated by Django 4.2.9 on 2024-08-04 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0022_alter_course_options_remove_course_file_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='cover_image',
            new_name='thumbnail',
        ),
    ]
