"""
Django settings for cme project.

Generated by 'django-admin startproject' using Django 4.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
from django.conf import settings


if not settings.DEBUG:

    import os

    # Build paths inside the project like this: BASE_DIR / 'subdir'.
    BASE_DIR = Path(__file__).resolve().parent.parent.parent


    # Quick-start development settings - unsuitable for production
    # See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

    # SECURITY WARNING: keep the secret key used in production secret!
    SECRET_KEY = 'django-insecure-32q031l#ontvh88lkxa-h4@h=4t82w*)t+rizmf9sp%arik7ow'

    # SECURITY WARNING: don't run with debug turned on in production!
    DEBUG = False

    ALLOWED_HOSTS = ['139.59.187.73', 'joincme.com', 'www.joincme.com', 'cmetradingacademy.com', 'www.cmetradingacademy.com']
    

    ADMINS = (
        # ("Nakasoft Support", "support@nakasoft.net"),
        ("Nakasoft Support", "support@nakasoft.com"),
    )


    # EMAIL_BACKEND = 'django.core.mail.backends.filebased.EmailBackend'
    # EMAIL_FILE_PATH = BASE_DIR / 'emails'


    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
    EMAIL_HOST = 'smtp.zoho.com' #'box.nakamail.com' #'smtp.gmail.com'
    EMAIL_HOST_USER = 'cme_noreply@nakasoft.com' #'lynton101@gmail.com'
    EMAIL_HOST_PASSWORD = 'Naka50ft@69' #'ikechukwu69'
    EMAIL_PORT = 587
    EMAIL_USE_TLS = True
    DEFAULT_FROM_EMAIL = EMAIL_HOST_USER
    SERVER_EMAIL = 'support@nakasoft.com'



    # Application definition
    INSTALLED_APPS = [
        'django.contrib.admin',
        'django.contrib.auth',
        'django.contrib.contenttypes',
        'django.contrib.humanize',
        'django.contrib.sites',
        'django.contrib.sessions',
        'django.contrib.messages',
        'django.contrib.staticfiles',
        #3rd party apps
        'crispy_forms',
        'crispy_bootstrap5',
        # 'rest_framework',
        'django_select2',
        'embed_video',
        'django_summernote',
        #custom apps
        'accounts',
        'affiliates',
        'core',
        'contact',
        'coupon',
        'courses',
        'plans',
        'payments',
        'dashboard',
    ]


    MIDDLEWARE = [
        'django.middleware.security.SecurityMiddleware',
        'django.contrib.sessions.middleware.SessionMiddleware',
        'django.middleware.common.CommonMiddleware',
        'django.middleware.csrf.CsrfViewMiddleware',
        'django.contrib.auth.middleware.AuthenticationMiddleware',
        'django.contrib.messages.middleware.MessageMiddleware',
        'django.middleware.clickjacking.XFrameOptionsMiddleware',
    ]

    ROOT_URLCONF = 'cme.urls'

    TEMPLATES = [
        {
            'BACKEND': 'django.template.backends.django.DjangoTemplates',
            'DIRS': [BASE_DIR /'templates'],
            'APP_DIRS': True,
            'OPTIONS': {
                'context_processors': [
                    'django.template.context_processors.debug',
                    'django.template.context_processors.media',
                    'django.template.context_processors.request',
                    'django.contrib.auth.context_processors.auth',
                    'django.contrib.messages.context_processors.messages',
                ],
            },
        },
    ]

    WSGI_APPLICATION = 'cme.wsgi.application'

    AUTH_USER_MODEL = 'accounts.User'


    # Database
    # https://docs.djangoproject.com/en/4.2/ref/settings/#databases

    # DATABASES = {
    #     'default': {
    #         'ENGINE': 'django.db.backends.sqlite3',
    #         'NAME': BASE_DIR / 'db.sqlite3',
    #     }
    # }

    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME':  'cme',
            'USER': 'cmeuser',
            'PASSWORD': 'cm3U53r@!',
            'HOST': 'localhost',
            'PORT': '5432',
        }
    }


    # We then modify our projects settings.py to use our custom user model and authentication backend.
    AUTH_USER_MODEL = "accounts.User"
    # AUTHENTICATION_BACKENDS = ["accounts.backends.CustomUserModelBackend"]
    AUTHENTICATION_BACKENDS = ["accounts.backends.ExtendedUserModelBackend"]



    # Password validation
    # https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

    AUTH_PASSWORD_VALIDATORS = [
        {
            'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
        },
        {
            'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        },
        {
            'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
        },
        {
            'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
        },
    ]


    # Internationalization
    # https://docs.djangoproject.com/en/4.2/topics/i18n/

    LANGUAGE_CODE = 'en-us'

    TIME_ZONE = 'Africa/Lagos' #'UTC'

    USE_I18N = True

    USE_TZ = True


    # Static files (CSS, JavaScript, Images)
    # https://docs.djangoproject.com/en/4.2/howto/static-files/

    STATIC_URL = 'static/'
    STATICFILES_DIRS = [
        BASE_DIR / "static",
    ]
    ## Use static_root and media_root files from droplet
    STATIC_ROOT = '/var/www/static-root/cme/'
    MEDIA_URL = 'media/'
    MEDIA_ROOT = '/var/www/media-root/cme/'


    # Default primary key field type
    # https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

    DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

    SHORT_DATE_FORMAT = 'd/m/Y'
    SHORT_DATETIME_FORMAT = 'd/m/Y P'

    CRISPY_ALLOWED_TEMPLATE_PACKS = 'bootstrap5'
    CRISPY_TEMPLATE_PACK = 'bootstrap5'
    SUMMERNOTE_THEME = 'bs5'  # Show summernote with Bootstrap5





    SITE_ID = 1




    X_FRAME_OPTIONS = 'SAMEORIGIN'
    # X_FRAME_OPTIONS = 'ALLOW-FROM https://joincme.com/'



    EMBED_VIDEO_BACKENDS = (
        'embed_video.backends.YoutubeBackend',
        # 'embed_video.backends.VimeoBackend',
        # 'embed_video.backends.SoundCloudBackend',
        # 'courses.backends.CustomBackend',
    )



    LOGIN_REDIRECT_URL = "home"
    LOGOUT_REDIRECT_URL = "home" #'/accounts/login/'



    DATA_UPLOAD_MAX_NUMBER_FIELDS = None #1000 # higher than the count of fields


    from ..cdn.conf import *
